### ISSUE TITLE
Call to undefined method teleinfoCmd::setEventOnly()

### ISSUE THREAD

**Issue by maxi768** [NextDom/plugin-teleinfo#151]
## Etapes à reproduire (pour les bugs)
1. Modification de l'affichage du plugin

## Environnement
* **Version Jeedom**: 4.2.7
* **Platform**:
* **Version du Plugin **: 2021-02-04 01:01:47
* **Type de modem**:
* **Compteur linky**:
* **Compteur standard ou historique**:

## Logs
```
0000|[Fri Feb 04 11:07:02.422631 2022] [php7:error] [pid 2538] [client 192.168.1.41:51027] PHP Fatal error:  Uncaught Error: Call to undefined method teleinfoCmd::setEventOnly() in /var/www/html/plugins/teleinfo/core/class/teleinfo.class.php:1023
0001|Stack trace:
0002|#0 /var/www/html/plugins/teleinfo/core/class/teleinfo.class.php(991): teleinfo->createOtherCmd()
0003|#1 /var/www/html/core/class/DB.class.php(232): teleinfo->postSave()
0004|#2 /var/www/html/core/class/eqLogic.class.php(1002): DB::save(Object(teleinfo), false)
0005|#3 /var/www/html/core/ajax/eqLogic.ajax.php(488): eqLogic->save()
0006|#4 {main}
0007|thrown in /var/www/html/plugins/teleinfo/core/class/teleinfo.class.php on line 1023, referer: http://192.168.1.14/index.php?v=d&m=teleinfo&p=teleinfo&id=139
```
Voir discussion sur forum : #https://community.jeedom.com/t/call-to-undefined-method-teleinfocmd-seteventonly/78071

**Comment by noyax** [comment]
Pour info: https://community.jeedom.com/t/modifications-plugin-teleinfo-checksum-en-mode-standard-traduction-du-champ-stge-traduction-du-champs-relais/76597

J'ai aussi fait une demande pour que ce soit intégré au code: https://github.com/NextDom/plugin-teleinfo/pull/150/

**Comment by Gis70** [comment]
Salut, j'ai la possibilité de merger, MAIS, va t'on casser la compatibilité avec Jeedom V4.1 ?

**Comment by maxi768** [comment]
Salut,
Je ne pense pas...regarde la discussion sur le forum jeedom il semble que cette fonction était "deprecied" depuis un petit moment..

https://community.jeedom.com/t/call-to-undefined-method-teleinfocmd-seteventonly/78071

**Comment by Gis70** [comment]
Pouvez vous tester ? c'est sur la develop. 

Fait moi signe et n'hésitez pas à faire des PR

**Comment by noyax** [comment]
tester quoi? Si ça fonctionne avec la 4.1? A part les 2 lignes que j'ai effacées pour rendre compatible avec la 4.2 le reste fonctionnait sous la V4.1 de jeedom

**Comment by Gis70** [comment]
tester que la branche develop fonctionne comme il faut sous jeedom v4.2, si oui alors je basculerai sur la master.

**Comment by noyax** [comment]
ok, je regarde ça demain

**Comment by noyax** [comment]
En regardant déjà avec winmerge je trouve une différence entre les fichiers 
- teleinfo.class.php en ligne 548 une condition a été rajoutée (une modification en attente de validation?). Je ne pense pas qu'il y ait de pb avec celle ci.
![image](https://user-images.githubusercontent.com/4825486/152630893-bf44108c-eb85-4fe9-823f-904654bef427.png)

- info.json a été modifié mais c'est pour indiquer les versions donc pas de pb je pense
![image](https://user-images.githubusercontent.com/4825486/152630869-46afa921-8544-4c0c-95dc-7beb467adaa8.png)

A priori cela ne devrait pas poser de problèmes. Je teste.

**Comment by noyax** [comment]
la différence dans le teleinfo.class.php est liée à l'intégration du #145 , ok

**Comment by noyax** [comment]
je viens d'uploader les fichiers de la branche develop et ça fonctionne. Je n'ai pas tout testé mais ça a l'air bon

**Comment by noyax** [comment]
Il reste à réparer l'affichage dans le panel santé mais là je ne sais pas trop quoi faire...

**Comment by Gis70** [comment]
oui j'ai incrémenté les versions et mis une version mini, je ne suis pas développeur non plus. Si tu trouves qqn capable de corriger ce qui ne va pas sur le forum.

**Comment by noyax** [comment]
J'ai essayé de passer les fichiers compatibles avec python V3. Est ce que quelqu'un pourrait essayer chez lui voir s'il n'y a pas de pb? De préférence en mode historique car je suis en standard chez moi. Cela résout aussi les pb d'affichage dans le panel https://github.com/noyax/plugin-teleinfo/tree/decode_stge_et_checksum

**Comment by Gis70** [comment]
C'est poussé, pour l'instant je laisse les fichiers txt et backup mais quand tout marchera bien on fera du nettoyage ;)

**Comment by noyax** [comment]
Dans le fichier permettant l'installation des dépendances il n'y a apparemment pas toutes celles nécessaires au bon fonctionnement du plugin. si les modules absents du fichier ont été installés par un autre plugin il n'y a pas de pb mais sinon cela ne fonctionne pas. Je vais essayer de faire la liste de tous les modules nécessaires et de compléter le fichier ce soir.

**Comment by noyax** [comment]
Petit point de la situation:
- passage en python3 => ok
- compteur mode historique => ok
- compteur mode standard => ok
- modem cartelectronic version 1 compteur => ok
- modem cartelectronic version 2 compteurs =>
             - si cavalier interne modem sur 1 compteur => ok => attirer l'attention sur la doc à ne pas cocher "modem caretelectronic 2 compteurs" dans configuration
             - si cavalier interne modem sur 2 compteurs => aucune idée si ça fonctionne ou pas, normalement oui mais...

- un peu de ménage dans les fichiers temporaires
- ajout du fichier packages.json pour profiter de l'évolution de la gestion des dépendances liée à jeedom en v4.2 https://blog.jeedom.com/6170-introduction-jeedom-4-2-installation-de-dependance/
- je ne sais plus... :)
