### ISSUE TITLE
Problem de thread

### ISSUE THREAD

**Issue by micromad** [NextDom/plugin-teleinfo#50]
## Description
Les logs de teleinfo font remonter des problemes de thread au niveau du script python.

## Contexte
Suivi de teleinfos avec deux compteurs Linky : un en production et un en consommation

## Environnement
* **Version Jeedom**: 3.2.7
* **Platform**: Rpi3 Debian Jessie (a jour)
* **Version du Plugin (ex: 2.6.0)**: 3.1.0
* **Type de modem**: cartelectronic sur rail
* **Compteur linky**: 
- [x] Oui 
- [ ] Non

* **Mode du compteur**: standard

## Logs
`[2018-05-20 19:36:18][INFO] : Vérification de l'état du service : NOK 
[2018-05-20 19:36:18][INFO] : Démarrage compteur de consommation
[2018-05-20 19:36:18][INFO] : --------- Informations sur le master --------
[2018-05-20 19:36:18][INFO] : Adresse             :http://192.168.1.73:80
[2018-05-20 19:36:18][INFO] : Host / Port         :192.168.1.73:80
[2018-05-20 19:36:18][INFO] : Path complémentaire :
[2018-05-20 19:36:18][INFO] : Mise en forme pour le service : http://192.168.1.73:80
[2018-05-20 19:36:18][INFO] : Debug : 0
[2018-05-20 19:36:18][INFO] : Force : 0
[2018-05-20 19:36:18][INFO] : Port modem : /dev/ttyUSB1
[2018-05-20 19:36:18][INFO] : Type : conso
[2018-05-20 19:36:18][INFO] : Mode : historique
[2018-05-20 19:36:18][INFO] : ---------------------------------------------
[2018-05-20 19:36:18][INFO] : Fonctionnement en mode 1 compteur
[2018-05-20 19:36:18][INFO] : Exécution du service : nice -n 19 /usr/bin/python /var/www/html/plugins/teleinfo/ressources/teleinfo.py -d 0 -p /dev/ttyUSB1 -v 1200 -e http://192.168.1.73:80 -c <cle_api> -f 0 -t conso -m historique -r /var/www/html/plugins/teleinfo/core/class
[2018-05-20 19:36:20][INFO] : Service OK
[2018-05-20 19:36:20][INFO] : ---------------------------------------------
[2018-05-20 19:36:20][INFO] : [Production] Mode local
[2018-05-20 19:36:20][INFO] : --------- Informations sur le master --------
[2018-05-20 19:36:20][INFO] : Adresse             :http://192.168.1.73:80
[2018-05-20 19:36:20][INFO] : Host / Port         :192.168.1.73:80
[2018-05-20 19:36:20][INFO] : Path complémentaire :
[2018-05-20 19:36:20][INFO] : Mise en forme pour le service : http://192.168.1.73:80
[2018-05-20 19:36:20][INFO] : Debug : 0
[2018-05-20 19:36:20][INFO] : Force : 0
[2018-05-20 19:36:20][INFO] : Port modem : /dev/ttyUSB0
[2018-05-20 19:36:20][INFO] : Type : prod
[2018-05-20 19:36:20][INFO] : Mode : standard
[2018-05-20 19:36:20][INFO] : ---------------------------------------------
[2018-05-20 19:36:20][INFO] : Fonctionnement en mode 1 compteur
[2018-05-20 19:36:20][INFO] : [Production] Exécution du service : nice -n 19 /usr/bin/python /var/www/html/plugins/teleinfo/ressources/teleinfo.py -d 0 -p /dev/ttyUSB0 -v 9600 -e http://192.168.1.73:80 -c <cle_api> -f 0 -t prod -m standard -r /var/www/html/plugins/teleinfo/core/class
[2018-05-20 19:36:23][INFO] : [Production] Service OK
[2018-05-20 19:36:23][INFO] : ---------------------------------------------
/bin/sh: 1: Syntax error: Unterminated quoted string
/bin/sh: 1: Syntax error: Unterminated quoted string
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/var/www/html/plugins/teleinfo/ressources/teleinfo.py", line 279, in target
    self.process = subprocess.Popen(self.cmd + send_data, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "/var/www/html/plugins/teleinfo/ressources/teleinfo.py", line 285, in timer_callback
    if self.process.poll() is None:
AttributeError: 'NoneType' object has no attribute 'poll'

Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/var/www/html/plugins/teleinfo/ressources/teleinfo.py", line 279, in target
    self.process = subprocess.Popen(self.cmd + send_data, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
`
et ainsi de suite...

**Comment by ticed35** [comment]
Plus de thread dans la base du démon en version 4.0.0
Utilisation de la librairie Jeedom qui l'implémente elle même.
