### ISSUE TITLE
Probleme apres la mise a jour du 06-03-2019

### ISSUE THREAD

**Issue by micromad** [NextDom/plugin-teleinfo#68]
## Description
Le deamon ne demarre plus apres la mise a jour du 2019-03-06 13:19:15

## Environnement
* **Version Jeedom**: 3.2.16
* **Platform**: Raspbian Jessie
* **Version du Plugin (ex: 2.6.0)**: core teleinfo 4.1.2
* **Type de modem**: Cartelectronic
* **Compteur linky**: 
- [x] Oui 
- [ ] Non

* **Mode du compteur**: standard et historique

## Logs

# Teleinfo deamon
[2019-03-06 15:31:44][INFO] : GLOBAL------Start teleinfod
[2019-03-06 15:31:44][INFO] : GLOBAL------Cycle Sommeil : 0.5
[2019-03-06 15:31:44][INFO] : GLOBAL------Socket port : 55062
[2019-03-06 15:31:44][INFO] : GLOBAL------Socket host : 127.0.0.1
[2019-03-06 15:31:44][INFO] : GLOBAL------Log level : info
[2019-03-06 15:31:44][INFO] : GLOBAL------Callback : http://127.0.0.1:80/plugins/teleinfo/core/php/jeeTeleinfo.php
[2019-03-06 15:31:44][INFO] : GLOBAL------Vitesse : 1200
[2019-03-06 15:31:44][INFO] : GLOBAL------Apikey : <key>
[2019-03-06 15:31:44][INFO] : GLOBAL------Cycle : 0.3
[2019-03-06 15:31:44][INFO] : GLOBAL------Port : /dev/ttyUSB1
[2019-03-06 15:31:44][INFO] : GLOBAL------Type : conso
[2019-03-06 15:31:44][INFO] : GLOBAL------Mode : historique
Traceback (most recent call last):
File "/var/www/html/plugins/teleinfo/ressources/teleinfo.py", line 392, in <module>
jeedom_utils.write_pid(str(globals.pidfile))
File "/var/www/html/plugins/teleinfo/ressources/jeedom/jeedom.py", line 194, in write_pid
file(path, 'w').write("%s
" % pid)
IOError: [Errno 2] No such file or directory: '/tmp/jeedom/teleinfo/teleinfo_conso.pid'
[2019-03-06 15:31:47][INFO] : GLOBAL------Start teleinfod
[2019-03-06 15:31:47][INFO] : GLOBAL------Cycle Sommeil : 0.5
[2019-03-06 15:31:47][INFO] : GLOBAL------Socket port : 55063
[2019-03-06 15:31:47][INFO] : GLOBAL------Socket host : 127.0.0.1
[2019-03-06 15:31:47][INFO] : GLOBAL------Log level : info
[2019-03-06 15:31:47][INFO] : GLOBAL------Callback : http://127.0.0.1:80/plugins/teleinfo/core/php/jeeTeleinfo.php
[2019-03-06 15:31:47][INFO] : GLOBAL------Vitesse : 9600
[2019-03-06 15:31:47][INFO] : GLOBAL------Apikey : <key>
[2019-03-06 15:31:47][INFO] : GLOBAL------Cycle : 0.3
[2019-03-06 15:31:47][INFO] : GLOBAL------Port : /dev/ttyUSB0
[2019-03-06 15:31:47][INFO] : GLOBAL------Type : prod
[2019-03-06 15:31:47][INFO] : GLOBAL------Mode : standard
Traceback (most recent call last):
File "/var/www/html/plugins/teleinfo/ressources/teleinfo.py", line 392, in <module>
jeedom_utils.write_pid(str(globals.pidfile))
File "/var/www/html/plugins/teleinfo/ressources/jeedom/jeedom.py", line 194, in write_pid
file(path, 'w').write("%s
" % pid)
IOError: [Errno 2] No such file or directory: '/tmp/jeedom/teleinfo/teleinfo_prod.pid'

# Teleinfo log
Clef API non valide, vous n'êtes pas autorisé à effectuer cette action (teleinfo)Terminating...
Terminating...

**Comment by micromad** [comment]
Le deamon vient de redemarrer mais affiche toutes les secondes :
[2019-03-06 15:45:48][INFO] : Starting new HTTP connection (1): 127.0.0.1
[2019-03-06 15:45:50][INFO] : Starting new HTTP connection (1): 127.0.0.1
[2019-03-06 15:45:51][INFO] : Starting new HTTP connection (1): 127.0.0.1

**Comment by ticed35** [comment]
Salut, pour les erreurs remontées c'est un problème de droit sur le répertoire /tmp/jeedom/. Le user jeedom ne doit pas avoir le droit write dessus. 
Pour les logs starting c'est une info pas d'erreur.

**Comment by ticed35** [comment]
@micromad, as-tu des problèmes de remonté d'info ?

**Comment by micromad** [comment]
Salut @ticed35,

non depuis le redemarrage du deamon, les infos remontent. De nouveaux champs ont ete crees comme ERQ1, ERQ2, ...
Ok pour le log info, mais le fichier va exploser !!! Pas moyen de mettre ce message sur un niveau plus important type warning ou debug ?

Encore merci pour la reactivite !!!

**Comment by ticed35** [comment]
@micromad, un moyen détourné une fois que ton démon est lancé clique sur remettre les logs en normal. Cela fera encore moins de logs. 
Je vais mettre ça dans ma todo list de plus afficher ce message en info.
